### ISSUE TITLE
SimpleCollection.isAvailable checks for wrong service

### ISSUE THREAD

**Issue by infeo** [swiesend/secret-service#27]
The SimpleCollection has the static `isAvailable()`method, to check wether the running OS has the gnome keyring service installed. But looking into the method, it actually only checks if the DBUS service is available.

https://github.com/swiesend/secret-service/blob/907b564670b7b2e617771712314ba1ba193ca4f4/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L168

The string to check should be `org.gnome.keyring`.

**Comment by swiesend** [comment]
Do you think it would be problematic to check for both?

**Comment by infeo** [comment]
The check for the DBUS service is redunant, is it not? Because in line 166 you connect to this service, if it would not exist, the method would fail.

About the freedesktop service: Is it always present if the gnome keyring is present? Or can it happen that the only the keyring is present and not the freedesktop service?

**Comment by swiesend** [comment]
1. Yes, the `org.freedesktop.DBus` check is kind of redundant, but does not hurt. I should remove it though because of Occam's razor...
2. As the `secret-service` library tries only to be a client for the Sercet Service it naturally should only depend on `org.freedesktop.secrets` as others (like `KeePassXC`) should be able provide the same service.
3. Practically speaking `org.gnome.keyring` should be expected, because without no prompt handling or collection unlocking without typing would be able. Thus there is the official:
  https://github.com/swiesend/secret-service/blob/9fb370568ed21cb45dec1323e29080e6d86cb8b1/src/main/java/org/gnome/keyring/interfaces/InternalUnsupportedGuiltRiddenInterface.java#L12

**Comment by purejava** [comment]
Yes, having gnome-keyring installed, calling `dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListActivatableNames` returns:
- "org.gnome.keyring" and
- "org.freedesktop.secrets"

whereas without gnome-keyring installed, none of the two is returned.

**Comment by purejava** [comment]
I agree with infeo.
From my point of view, checking for 'org.gnome.keyring' is a good choice, as this might be more specific.
